"""FeuerON CSV import data models."""

from scripts.feueron.models.addresses import (
    AddressRecord,
    AdrErb,
    AdrKontakte,
    AdrSta,
)
from scripts.feueron.models.base import (
    AdrTelArt,
    AusbildungErfolg,
    BeitragArt,
    FeuerONBase,
    FeuerONBool,
    FeuerONDate,
    FeuerONRecord,
    FeuerONTime,
    FeuerONTimestamp,
    Geschlecht,
    PrModul,
    TelArt,
    Zahlungsweise,
    generate_csv,
)
from scripts.feueron.models.equipment import (
    EquipmentRecord,
    PrPruf,
    PrsFme,
    PrsFp,
    PrsFuge,
    PrsEm,
    PrsLager,
    PrStamm,
)
from scripts.feueron.models.persons import (
    PersonRecord,
    PvAbt,
    PvAbwes,
    PvAbzna,
    PvAngehoer,
    PvArbgb,
    PvAusb,
    PvAusw,
    PvBank,
    PvBeitrag,
    PvBeruf,
    PvBeurl,
    PvBiog,
    PvDb,
    PvDnGr,
    PvDnSt,
    PvEhrg,
    PvFamst,
    PvFsche,
    PvFunkt,
    PvGrupp,
    PvMagaz,
    PvSprach,
    PvTelep,
    PvUbort,
    PvUntsu,
    PvVerf,
)

__all__ = [
    # Base
    "FeuerONBase",
    "FeuerONRecord",
    "FeuerONBool",
    "FeuerONDate",
    "FeuerONTime",
    "FeuerONTimestamp",
    "generate_csv",
    # Enums
    "AdrTelArt",
    "AusbildungErfolg",
    "BeitragArt",
    "Geschlecht",
    "PrModul",
    "TelArt",
    "Zahlungsweise",
    # Person models
    "PersonRecord",
    "PvDb",
    "PvAbt",
    "PvAbwes",
    "PvAbzna",
    "PvAngehoer",
    "PvArbgb",
    "PvAusb",
    "PvAusw",
    "PvBank",
    "PvBeitrag",
    "PvBeruf",
    "PvBeurl",
    "PvBiog",
    "PvDnGr",
    "PvDnSt",
    "PvEhrg",
    "PvFamst",
    "PvFsche",
    "PvFunkt",
    "PvGrupp",
    "PvMagaz",
    "PvSprach",
    "PvTelep",
    "PvUbort",
    "PvUntsu",
    "PvVerf",
    # Equipment models
    "EquipmentRecord",
    "PrStamm",
    "PrsEm",
    "PrsFme",
    "PrsFuge",
    "PrsFp",
    "PrsLager",
    "PrPruf",
    # Address models
    "AddressRecord",
    "AdrSta",
    "AdrErb",
    "AdrKontakte",
]
