"""FeuerON REST API client."""

from scripts.feueron.api.client import FeuerONAPIError, FeuerONAuthError, FeuerONClient
from scripts.feueron.api.einsatzdienst import EinsatzdienstMixin
from scripts.feueron.api.feuerwehr import FeuerwehrMixin
from scripts.feueron.api.finanzen import FinanzenMixin
from scripts.feueron.api.models import (
    Abteilung,
    AbteilungValue,
    Bankverbindung,
    Beitrag,
    ContextInfo,
    CreateAbteilung,
    CreateAbteilungEntry,
    CreateAdresse,
    CreateDienstgradEntry,
    CreateBankverbindungEntry,
    CreateBeitragEntry,
    CreateErreichbarkeiten,
    CreateGruppeEntry,
    CreateOrganisation,
    CreatePersonRequest,
    Dienstgrad,
    DienstgradLabel,
    DienstgradValue,
    Erreichbarkeit,
    GeneralMenu,
    Geschlecht,
    Gruppe,
    I18nText,
    MenuItem,
    Organisation,
    OrganisationTree,
    OrganisationTreeNode,
    OrganisationsEbene,
    Person,
    PersonDetail,
    UserSettings,
    Verfahren,
    Zahlungen,
)
from scripts.feueron.api.person import PersonMixin
from scripts.feueron.api.reference import ReferenceMixin

__all__ = [
    "Abteilung",
    "AbteilungValue",
    "Bankverbindung",
    "Beitrag",
    "ContextInfo",
    "CreateAbteilung",
    "CreateAbteilungEntry",
    "CreateAdresse",
    "CreateDienstgradEntry",
    "CreateBankverbindungEntry",
    "CreateBeitragEntry",
    "CreateErreichbarkeiten",
    "CreateGruppeEntry",
    "CreateOrganisation",
    "CreatePersonRequest",
    "Dienstgrad",
    "DienstgradLabel",
    "DienstgradValue",
    "EinsatzdienstMixin",
    "Erreichbarkeit",
    "FeuerONAPIError",
    "FeuerONAuthError",
    "FeuerONClient",
    "FeuerwehrMixin",
    "FinanzenMixin",
    "GeneralMenu",
    "Geschlecht",
    "Gruppe",
    "I18nText",
    "MenuItem",
    "Organisation",
    "OrganisationTree",
    "OrganisationTreeNode",
    "OrganisationsEbene",
    "Person",
    "PersonDetail",
    "PersonMixin",
    "ReferenceMixin",
    "UserSettings",
    "Verfahren",
    "Zahlungen",
]
